### ISSUE TITLE
Style tiles

### ISSUE THREAD

**Issue by noakressel** [shenkarlab/J14#12]
2 options for styling the project.
Noa - 1 style tile
Yael - 1 style tile

**Comment by mushon** [comment]
Please post them here and then close the ticket. Thanks!

**Comment by ohadsas** [comment]
@mushon  Post what? Noa opened this issue by mistake, and then she opened a new one.
Issues cannot be deleted so we closed it instead without registering this issue to a milestone nor a due date.

**Comment by mushon** [comment]
Ok, I just wanted to suggest you post the styletiles in the issues. 
Also, it is good practice to close an issue with a note for why it is being closed (usually a reference to a code committed). When an issue is closed because it's a duplicate you can me soon it by writing the number of that other issue like this: #13

**Comment by ohadsas** [comment]
Closing this issue - this is a duplication of : https://github.com/shenkarlab/J14/issues/13
